'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import { ArrowRight, Check, ChevronDown, ChevronRight, Globe2, HeartHandshake, LockKeyhole, Menu, NotebookPen, ShieldCheck, Sparkles, X } from 'lucide-react'
import { Header as SiteHeader, Footer as SiteFooter } from './site-shell'

const services = [
  { title: 'Nikah Services', text: 'A considered Islamic ceremony arranged around your family, location and preferred format.', icon: HeartHandshake },
  { title: 'Online Nikah', text: 'Guided remote participation for couples and families who cannot be together in one place.', icon: Globe2 },
  { title: 'Nikah for Overseas Pakistanis', text: 'Practical coordination for couples in Pakistan and abroad, with clear documentation guidance.', icon: ShieldCheck },
  { title: 'Nikah Nama Preparation', text: 'Accurate preparation and review of the Nikah Nama before the ceremony takes place.', icon: NotebookPen },
  { title: 'Marriage Registration Assistance', text: 'Support understanding the local registration process after the Islamic Nikah.', icon: Check },
  { title: 'Marriage Certificate Assistance', text: 'Case-specific guidance on certificates and documents needed for intended use.', icon: Sparkles },
]

const faqs = [
  ['How many witnesses are required for a Nikah?', 'A Nikah requires witnesses who meet the relevant Islamic requirements. The exact arrangements should be confirmed for your circumstances before the ceremony.'],
  ['Is a Nikah Khawan provided?', 'We can help coordinate a suitable Nikah Khawan or work with one selected by your family, subject to availability and location.'],
  ['Is a Wali required?', 'Requirements around the Wali can depend on the parties, school of thought and circumstances. We discuss this with you before making arrangements.'],
  ['How is Haq Mehr recorded?', 'The agreed Haq Mehr is discussed by the parties and accurately recorded in the Nikah Nama as part of the ceremony documentation.'],
  ['Can the Nikah take place online?', 'Online participation may be possible in suitable circumstances. Whether it is appropriate or recognised for your intended use depends on the parties, location and applicable requirements.'],
  ['Does a Nikah Nama prove civil marriage everywhere?', 'No. An Islamic Nikah and civil registration are distinct stages. Recognition, registration and certificate requirements vary by jurisdiction and intended use.'],
]

function Logo() {
  return <Link href="#top" className="flex items-center gap-3" aria-label="Nikah House home"><span className="flex size-10 items-center justify-center rounded-full border border-[#c9a96e]/60 text-[#c9a96e]"><span className="font-serif text-xl">N</span></span><span className="font-serif text-xl tracking-tight text-[#f8f4ed]">Nikah <span className="text-[#d7b878]">House</span></span></Link>
}

export function Header() {
  const [open, setOpen] = useState(false)
  return <header className="absolute inset-x-0 top-0 z-20"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10"><Logo /><nav className="hidden items-center gap-8 text-sm text-white/75 lg:flex"><Link href="#services" className="transition hover:text-white">Services <ChevronDown className="ml-1 inline size-3" /></Link><Link href="#process" className="transition hover:text-white">How it works</Link><Link href="#faqs" className="transition hover:text-white">FAQs</Link><Link href="#about" className="transition hover:text-white">About</Link></nav><Link href="#enquire" className="hidden rounded-full bg-[#d7b878] px-5 py-3 text-sm font-semibold text-[#142435] transition hover:bg-[#e8cf99] lg:inline-flex">Discuss Your Nikah <ArrowRight className="ml-2 size-4" /></Link><button type="button" onClick={() => setOpen(!open)} className="rounded-full border border-white/20 p-2 text-white lg:hidden" aria-expanded={open} aria-label={open ? 'Close menu' : 'Open menu'}>{open ? <X /> : <Menu />}</button></div>{open && <div className="mx-4 rounded-2xl border border-white/10 bg-[#142435] p-5 shadow-2xl lg:hidden"><nav className="flex flex-col gap-4 text-sm text-white/80"><Link href="#services" onClick={() => setOpen(false)}>Services</Link><Link href="#process" onClick={() => setOpen(false)}>How it works</Link><Link href="#faqs" onClick={() => setOpen(false)}>FAQs</Link><Link href="#about" onClick={() => setOpen(false)}>About</Link><Link href="#enquire" onClick={() => setOpen(false)} className="mt-2 rounded-full bg-[#d7b878] px-4 py-3 text-center font-semibold text-[#142435]">Discuss Your Nikah</Link></nav></div>}</header>
}

function SectionIntro({ eyebrow, title, text, light = false }) { return <div className={`max-w-2xl ${light ? 'text-white' : ''}`}><p className="mb-4 text-xs font-semibold uppercase tracking-[0.24em] text-[#ad8750]">{eyebrow}</p><h2 className="font-serif text-4xl leading-tight tracking-tight md:text-5xl">{title}</h2>{text && <p className={`mt-5 max-w-xl text-lg leading-8 ${light ? 'text-white/65' : 'text-[#5d6263]'}`}>{text}</p>}</div> }

function ServiceCard({ service }) { const Icon = service.icon; return <article className="group border-t border-[#d7d0c4] py-7 transition hover:border-[#ad8750]"><div className="mb-6 flex items-center justify-between"><Icon className="size-6 text-[#ad8750]" strokeWidth={1.4} /><ChevronRight className="size-4 text-[#9a9a92] transition group-hover:translate-x-1 group-hover:text-[#ad8750]" /></div><h3 className="font-serif text-2xl text-[#142435]">{service.title}</h3><p className="mt-3 leading-7 text-[#666b69]">{service.text}</p></article> }

function Timeline() { const steps = [{ n: '01', title: 'Initial discussion', text: 'Tell us about the parties, location, preferred date and intended use of your documents.' }, { n: '02', title: 'Requirements review', text: 'We clarify Islamic ceremony requirements, witnesses, Wali, Haq Mehr and documentation.' }, { n: '03', title: 'Nikah arranged', text: 'Your Nikah is coordinated with the relevant people, format and practical details in place.' }, { n: '04', title: 'Documentation guidance', text: 'We explain the next steps for Nikah Nama, registration and certificates for your case.' }]; return <div className="mt-14 grid gap-8 md:grid-cols-4">{steps.map((step) => <div key={step.n} className="relative border-t border-[#d7b878] pt-5"><span className="font-serif text-3xl text-[#ad8750]">{step.n}</span><h3 className="mt-7 font-serif text-2xl text-[#f8f4ed]">{step.title}</h3><p className="mt-3 text-sm leading-7 text-white/60">{step.text}</p></div>)}</div> }

export function Footer() { return <footer className="bg-[#101d2a] px-6 py-14 text-white lg:px-10"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[1.4fr_1fr_1fr_1.4fr]"><div><Logo /><p className="mt-6 max-w-xs text-sm leading-7 text-white/55">Professional Nikah, online Nikah and marriage-documentation guidance for couples in Pakistan and overseas.</p></div><div><h3 className="text-xs font-semibold uppercase tracking-[0.2em] text-[#d7b878]">Explore</h3><div className="mt-5 flex flex-col gap-3 text-sm text-white/60"><Link href="#services">Services</Link><Link href="#process">How it works</Link><Link href="#faqs">FAQs</Link></div></div><div><h3 className="text-xs font-semibold uppercase tracking-[0.2em] text-[#d7b878]">Coverage</h3><p className="mt-5 text-sm leading-7 text-white/60">Karachi · Lahore · Islamabad · Rawalpindi · Faisalabad<br />Overseas Pakistani couples</p></div><div><h3 className="text-xs font-semibold uppercase tracking-[0.2em] text-[#d7b878]">Important to know</h3><p className="mt-5 text-sm leading-7 text-white/55">Nikah House provides coordination and documentation guidance. Islamic Nikah, civil registration and overseas recognition are distinct matters. Requirements vary by jurisdiction and circumstances. This website is not a substitute for legal advice.</p></div></div><div className="mx-auto mt-14 flex max-w-7xl flex-col gap-3 border-t border-white/10 pt-6 text-xs text-white/35 sm:flex-row sm:justify-between"><span>© 2026 Nikah House. All rights reserved.</span><span>Confidential discussions · Case-specific guidance</span></div></footer> }

function Homepage() { return <><SiteHeader /><main id="top"><section className="relative isolate min-h-[720px] overflow-hidden bg-[#142435]"><Image src="/images/nikah-hero.png" alt="A quiet Nikah ceremony setting" fill priority className="object-cover object-center opacity-45" /><div className="absolute inset-0 bg-gradient-to-r from-[#142435] via-[#142435]/85 to-[#142435]/25" /><div className="relative mx-auto flex min-h-[720px] max-w-7xl items-end px-6 pb-20 pt-40 lg:px-10 lg:pb-28"><div className="max-w-3xl text-white"><p className="mb-6 text-xs font-semibold uppercase tracking-[0.28em] text-[#d7b878]">Nikah · Documentation · Guidance</p><h1 className="max-w-3xl font-serif text-5xl leading-[1.05] tracking-tight md:text-7xl">Professional Nikah Services for Couples in Pakistan and Overseas</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/70">A calm, professional way to arrange your Islamic Nikah, prepare your documents and understand the steps that may follow. Every couple&apos;s circumstances are considered individually.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="#enquire" className="inline-flex items-center justify-center rounded-full bg-[#d7b878] px-6 py-3.5 font-semibold text-[#142435] transition hover:bg-[#e8cf99]">Discuss Your Nikah <ArrowRight className="ml-2 size-4" /></Link><Link href="#services" className="inline-flex items-center justify-center rounded-full border border-white/30 px-6 py-3.5 font-semibold text-white transition hover:border-white hover:bg-white/10">Explore Services</Link></div></div></div></section>
<section id="about" className="bg-[#f7f3ec] px-6 py-24 lg:px-10"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[1fr_1.1fr] lg:items-center"><SectionIntro eyebrow="A considered beginning" title="Your ceremony and your documents deserve equal care." text="An Islamic Nikah, the preparation of a Nikah Nama, civil registration and recognition for use overseas are connected — but they are not the same thing. We help you see the full picture before arrangements begin." /><div className="grid gap-8 border-l border-[#d7b878] pl-7 text-[#5d6263]"><div><h3 className="font-serif text-2xl text-[#142435]">The religious ceremony</h3><p className="mt-2 leading-7">A Nikah is arranged around consent, witnesses, Wali where applicable and the agreed Haq Mehr.</p></div><div><h3 className="font-serif text-2xl text-[#142435]">The paper trail</h3><p className="mt-2 leading-7">The Nikah Nama and any registration or certificate steps depend on the location, parties and intended use.</p></div></div></div></section>
<section id="services" className="bg-[#fbfaf7] px-6 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="Our services" title="Support for the ceremony, and what comes after." text="From a local family Nikah to a carefully coordinated online arrangement, our role is to make the process clearer and more manageable." /><div className="mt-14 grid gap-x-10 md:grid-cols-2 lg:grid-cols-3">{services.map((service) => <ServiceCard key={service.title} service={service} />)}</div></div></section>
<section id="process" className="bg-[#142435] px-6 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><SectionIntro light eyebrow="How your Nikah is arranged" title="A clear process, from first conversation to next steps." text="We keep communication direct and discreet, so you understand what is being arranged and why." /><Timeline /></div></section>
<section className="bg-[#f7f3ec] px-6 py-24 lg:px-10"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[1.1fr_1fr] lg:items-center"><div className="relative aspect-[4/3] overflow-hidden"><Image src="/images/nikah-ceremony.png" alt="Nikah Nama preparation on a ceremony table" fill className="object-cover" /></div><div><SectionIntro eyebrow="Prepared with care" title="Documents commonly required" text="The exact list depends on your circumstances and the authority or country where documents will be used. We help you identify what applies before you proceed." /><ul className="mt-8 grid gap-4 text-[#424b4c] sm:grid-cols-2">{['CNIC or passport details', 'Photographs, where required', 'Witness identification', 'Details of Wali, where applicable', 'Agreed Haq Mehr', 'Prior marriage documents, if relevant'].map((item) => <li key={item} className="flex gap-3 text-sm leading-6"><Check className="mt-1 size-4 shrink-0 text-[#ad8750]" />{item}</li>)}</ul></div></div></section>
<section className="bg-[#fbfaf7] px-6 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="Why Nikah House" title="Professionalism in the details that matter." /><div className="mt-14 grid gap-10 md:grid-cols-3"><div><LockKeyhole className="size-7 text-[#ad8750]" strokeWidth={1.4} /><h3 className="mt-5 font-serif text-2xl text-[#142435]">Confidentiality</h3><p className="mt-3 leading-7 text-[#666b69]">Your family circumstances and documents are handled with discretion from the first enquiry.</p></div><div><HeartHandshake className="size-7 text-[#ad8750]" strokeWidth={1.4} /><h3 className="mt-5 font-serif text-2xl text-[#142435]">Proper consent</h3><p className="mt-3 leading-7 text-[#666b69]">We make space for the questions and requirements that help a ceremony proceed with clarity.</p></div><div><NotebookPen className="size-7 text-[#ad8750]" strokeWidth={1.4} /><h3 className="mt-5 font-serif text-2xl text-[#142435]">Accurate documents</h3><p className="mt-3 leading-7 text-[#666b69]">Names, details and intended use are considered carefully — because the paper trail matters.</p></div></div></div></section>
<section id="faqs" className="bg-[#f7f3ec] px-6 py-24 lg:px-10"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.8fr_1.2fr]"><SectionIntro eyebrow="Frequently asked" title="Practical answers before you begin." text="These are general answers. Your exact requirements may depend on the parties, location and intended use of your documents." /><div className="divide-y divide-[#d7d0c4] border-y border-[#d7d0c4]">{faqs.map(([question, answer]) => <details key={question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-serif text-xl text-[#142435]"><span>{question}</span><ChevronDown className="size-5 shrink-0 text-[#ad8750] transition group-open:rotate-180" /></summary><p className="max-w-2xl pt-4 pr-8 leading-7 text-[#666b69]">{answer}</p></details>)}</div></div></section>
<section id="enquire" className="bg-[#d7b878] px-6 py-20 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-[#536060]">Start with a conversation</p><h2 className="mt-4 max-w-2xl font-serif text-4xl leading-tight text-[#142435] md:text-5xl">Tell us what you need your Nikah to look like.</h2></div><Link href="mailto:hello@nikahhouse.com" className="inline-flex shrink-0 items-center rounded-full bg-[#142435] px-6 py-4 font-semibold text-white transition hover:bg-[#20364a]">Discuss Your Nikah <ArrowRight className="ml-2 size-4" /></Link></div></section></main><SiteFooter /></> }

export { ServiceCard, Timeline }

// JSON-LD is intentionally kept in the page component so the structured data matches visible content.
export function Schema() { return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@graph': [{ '@type': 'Organization', name: 'Nikah House', url: 'https://nikahhouse.com', description: 'Professional Nikah, online Nikah and marriage-documentation guidance for couples in Pakistan and overseas.' }, { '@type': 'WebSite', name: 'Nikah House', url: 'https://nikahhouse.com' }, { '@type': 'Service', name: 'Nikah Services', provider: { '@type': 'Organization', name: 'Nikah House' }, areaServed: ['Pakistan', 'Overseas Pakistani couples'], serviceType: 'Nikah and marriage documentation guidance' }, { '@type': 'FAQPage', mainEntity: faqs.map(([name, text]) => ({ '@type': 'Question', name, acceptedAnswer: { '@type': 'Answer', text } })) }] }) }} /> }

export function HomeWithSchema() { return <><Schema /><Homepage /></> }

export default HomeWithSchema